Release Varnish Cache 6.5.1
varnishcache/varnish-cache pull request #3419
Opened 2020-09-24 13:47 UTC by mbgrydeland

We need a new release in order to fix up the lack of bumping of VRT_MAJOR_VERSION in 6.5.0.

2020-09-24 20:04 UTC, Dridi requested changes

2020-09-24 20:04 UTC, Dridi commented on doc/sphinx/whats-new/upgrading-6.5.rst
> +  with the Hitch default configuration, making it easier to setup Varnish
s/setup Varnish/set Varnish up/ (I think)

2020-09-24 20:04 UTC, Dridi commented on doc/sphinx/whats-new/upgrading-6.5.rst
> +* The default systemd `varish.service` unit file now enables the HTTP/2
s/varish/varnish/

2020-09-24 21:21 UTC, feld commented
`docs/changes.rst` for 6.5.0 didn't update the changelog section header. It still reads **NEXT (scheduled 2020-09-15)**

2020-09-25 09:09 UTC, mbgrydeland commented on doc/sphinx/whats-new/upgrading-6.5.rst
> +  with the Hitch default configuration, making it easier to setup Varnish
Resolved by force push

2020-09-25 09:09 UTC, mbgrydeland commented on doc/sphinx/whats-new/upgrading-6.5.rst
> +* The default systemd `varish.service` unit file now enables the HTTP/2
Resolved by force push

2020-09-25 09:13 UTC, merged