Add {req,resp,bereq,beresp,obj}.time
varnishcache/varnish-cache pull request #3562
Opened 2021-03-25 16:30 UTC by nigoroll

See https://github.com/varnishcache/varnish-cache/pull/3553#issuecomment-804133604

Reviewers please let me know what think about this: We could have more & better assertions on `(ctx)->where`. If we want them, I would propose to add some utility macros like

```
#define VRT_CHECK_req(ctx) ...
#define VRT_CHECK_oc(ctx) ...
...

#define VRT_ACCESS_req(ctx) ...
#define VRT_ACCESS_oc(ctx) ...
...
```

such that we can generalize macros

2021-04-19 12:38 UTC, hermunn commented
Should there be some text somewhere about what happens for retries and restarts? Maybe something like, _if a retry occurs, bereq.time will be updated again before `sub vcl_backend_fetch` is called for the retry_.

2021-04-19 13:41 UTC, nigoroll commented
@hermunn sure we can have that just to be make it clear

2021-05-10 13:35 UTC, nigoroll commented
bugwash: @Dridi and me to discuss in light of our timeouts reform proposal

2021-09-08 19:08 UTC, Dridi requested changes
I don't think we need to look at this through the timeout lens, and this is a very tidy diff very pleasant to review!

I would like to see small changes:

- @hermunn's suggested clarification regarding restarts and retries
- new symbols limited to VCL >= 4.1
- `beresp.time` in `vcl_backend_error` (same as `resp.time` in `vcl_synth`)

Another suggestion on top of this change, should we consider`obj.age` too?

2021-09-20 13:02 UTC, nigoroll commented
todo note from discussion with @Dridi 

>     * @hermunn's suggested clarification regarding restarts and retries

yes

>     * new symbols limited to VCL >= 4.1

please, no

>     * `beresp.time` in `vcl_backend_error` (same as `resp.time` in `vcl_synth`)

yes

> Another suggestion on top of this change, should we consider`obj.age` too?

@bsdphk has already done this for me in 2016 :)  81913d93d978f45bfa49b65321cb49e4f1e8ad88

2021-11-25 16:23 UTC, hermunn approved these changes
Looks very good, thanks!

2021-11-26 08:13 UTC, Dridi commented
@nigoroll the size increase of `struct req` requires these adjustments:

```diff
--- bin/varnishtest/tests/r02219.vtc
+++ bin/varnishtest/tests/r02219.vtc
@@ -22,7 +22,7 @@ varnish v1 -arg "-p workspace_client=9k" \
 } -start
 
 client c1 {
-       send "PROXY TCP4 127.0.0.1 127.0.0.1 1111 2222\r\nGET /${string,repeat,752,A} HTTP/1.1\r\n\r\n"
+       send "PROXY TCP4 127.0.0.1 127.0.0.1 1111 2222\r\nGET /${string,repeat,744,A} HTTP/1.1\r\n\r\n"
        rxresp
 } -run
 
@@ -39,6 +39,6 @@ ${string,repeat,732,"42 "}
 } -run
 
 client c3 {
-       send "PROXY TCP4 127.0.0.1 127.0.0.1 1111 2222\r\nGET /${string,repeat,756,C} HTTP/1.1\r\n\r\n"
+       send "PROXY TCP4 127.0.0.1 127.0.0.1 1111 2222\r\nGET /${string,repeat,748,C} HTTP/1.1\r\n\r\n"
        rxresp
 } -run
```

2021-11-29 14:46 UTC, merged

2021-12-15 13:47 UTC, Dridi commented
I just realized that `bereq.time` is not available in `vcl_pipe`. @nigoroll, was it on purpose?

2021-12-16 07:40 UTC, Dridi commented
https://github.com/varnishcache/varnish-cache/pull/3759