Build VSC generated sources in lib/libvsc
varnishcache/varnish-cache pull request #3701
Opened 2021-09-20 10:53 UTC by mbgrydeland

This is to resolve the chicken and egg problem of the VSC headers being
generated only once bin/varnishd is built, while they are used in several
VMODs and libraries.

This moves the generation of the VSC .c and .h header files to a directory
in lib that can be built earlier than its dependencies.

2021-09-20 13:10 UTC, nigoroll approved these changes
I have not seen any build issues on sunos, tested in-tree and out-of-tree build

2021-09-27 05:40 UTC, Dridi requested changes
Please update `.gitignore` with the new paths.

2021-09-27 09:38 UTC, mbgrydeland commented
> Please update `.gitignore` with the new paths.

Done

2021-10-04 13:17 UTC, Dridi approved these changes

2021-10-04 13:17 UTC, merged